# NumPy Essentials for Data Science

---

### 🗂️ Topics Covered Today

| # | Topic |
|---|-------|
| 1 | What is NumPy? |
| 2 | NumPy vs Python Lists |
| 3 | Importing NumPy |
| 4 | Array Creation Methods |
| 5 | Array Attributes |
| 6 | 1D Indexing and Slicing |
| 7 | 2D Arrays |
| 8 | 2D Indexing and Slicing |
| 9 | Mathematical / Vectorized Operations |
| 10 | Aggregation Functions |
| 11 | Boolean Masking / Filtering |
| 12 | np.where() |
| 🏋️ | Practice Questions |

---

## 📌 Topic 1: What is NumPy?

### 🧑‍🏫 Theory

**NumPy** stands for **Numerical Python**.  
It is the most important library in Python for working with **numbers**, **arrays**, and **mathematical operations**.

Think of NumPy as a **super-powered calculator** that can work on thousands of numbers at once — much faster than regular Python.

### 🔑 Why is NumPy important?

- It is the **foundation** of almost every Data Science and Machine Learning library (like Pandas, Scikit-learn, TensorFlow).
- It stores data in a special structure called an **ndarray** (N-dimensional array).
- It performs operations **very fast** because it is written in C internally.
- It supports operations on entire arrays without writing loops.

### 🏫 Real-life Analogy

Imagine you have 1000 students' marks in a list.  
With regular Python, you would need to write a loop to add 5 bonus marks to each student.  
With NumPy, you just write: `marks + 5` — and it applies to **all 1000 students at once!** ⚡

---

## 📌 Topic 2: NumPy vs Python Lists

### 🧑‍🏫 Theory

Python already has **lists** to store multiple values. Then why do we need NumPy?

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Speed | Slower | Much Faster |
| Memory | Uses more memory | Uses less memory |
| Math operations | Need loops | Works directly on full array |
| Data type | Can mix types (int, str, etc.) | All elements must be same type |
| Dimensions | Only 1D easily | Supports 1D, 2D, 3D, ... |

### 🏫 Simple Comparison

Suppose you want to **double every element** in a list of numbers:

- **Python list**: You need a `for` loop or list comprehension.
- **NumPy array**: Just write `array * 2` — that's it!

This is called **vectorized operation** and is one of NumPy's biggest superpowers.

In [1]:
import numpy as np

In [2]:
# ============================================================
# TOPIC 2 EXAMPLE: NumPy vs Python Lists
# ============================================================

import numpy as np  # We'll formally learn this in Topic 3

# --- Python list approach ---
py_list = [10, 20, 30, 40, 50]

# To double each element in a Python list, we need a loop
doubled_list = [x * 2 for x in py_list]
print("Python List (doubled):", doubled_list)

# --- NumPy array approach ---
np_array = np.array([10, 20, 30, 40, 50])

# With NumPy, no loop needed — works directly!
doubled_array = np_array * 2
print("NumPy Array (doubled):", doubled_array)

print()
print("Type of Python List:", type(py_list))
print("Type of NumPy Array:", type(np_array))

Python List (doubled): [20, 40, 60, 80, 100]
NumPy Array (doubled): [ 20  40  60  80 100]

Type of Python List: <class 'list'>
Type of NumPy Array: <class 'numpy.ndarray'>


In [2]:
# ============================================================
# Speed Comparison: Python List vs NumPy Array
# ============================================================

import time

size = 1000000  # One million elements

# Python List speed test
py_list = list(range(size))
start = time.time()
result = [x * 2 for x in py_list]
end = time.time()
print(f"Python List time: {(end - start) * 1000:.2f} ms")

# NumPy Array speed test
np_array = np.arange(size)
start = time.time()
result = np_array * 2
end = time.time()
print(f"NumPy Array time: {(end - start) * 1000:.2f} ms")

print()
print("✅ NumPy is significantly faster than Python lists for large data!")

Python List time: 106.47 ms
NumPy Array time: 22.83 ms

✅ NumPy is significantly faster than Python lists for large data!


---

## 📌 Topic 3: Importing NumPy


```python
import numpy as np
```

- `import numpy` → loads the NumPy library
- `as np` → gives it a **short nickname** called `np`

So instead of writing `numpy.array(...)` every time, we can simply write `np.array(...)`.  
The alias `np` is a **universal convention** — everyone in the Data Science community uses it!

### 🔍 Check NumPy Version

You can also check which version of NumPy is installed using `np.__version__`.

In [1]:
# ============================================================
# TOPIC 3 EXAMPLE: Importing NumPy
# ============================================================

# Standard way to import NumPy — always use this!
import numpy as np

# Check the version of NumPy installed
print("NumPy Version:", np.__version__)

print()
print("✅ NumPy imported successfully! We are ready to use 'np' as our shortcut.")

NumPy Version: 2.4.6

✅ NumPy imported successfully! We are ready to use 'np' as our shortcut.


---

## 📌 Topic 4: Array Creation

### 🧑‍🏫 Theory

An **array** in NumPy is like a container that holds a fixed number of items, all of the **same data type**.  
NumPy gives us many ways to create arrays. Let's learn them one by one.

---

### 4.1 `np.array()` — Create from a Python list

This is the most basic way. You pass a **Python list** and it becomes a NumPy array.

```python
np.array([1, 2, 3, 4, 5])
```

---

### 4.2 `np.arange()` — Create a range of numbers

Similar to Python's `range()`, but returns a NumPy array.

```python
np.arange(start, stop, step)
```
- `start`: where to begin (inclusive)
- `stop`: where to end (**exclusive** — not included)
- `step`: how much to jump each time

---

### 4.3 `np.zeros()` — Array filled with zeros

Creates an array where every element is **0**. You just provide the size.

```python
np.zeros(5)          # 1D array of 5 zeros
np.zeros((3, 4))     # 2D array: 3 rows, 4 columns — all zeros
```

---

### 4.4 `np.ones()` — Array filled with ones

Same as `np.zeros()`, but every element is **1**.

```python
np.ones(5)           # 1D array of 5 ones
np.ones((2, 3))      # 2D array: 2 rows, 3 columns — all ones
```

---

### 4.5 `np.full()` — Array filled with a specific value

Creates an array filled with **any value you choose**.

```python
np.full(5, 7)        # Array of five 7s: [7, 7, 7, 7, 7]
np.full((2, 3), 9)  # 2D array, all filled with 9
```

---

### 4.6 `np.linspace()` — Evenly spaced numbers over a range

Creates a specified **number of evenly spaced values** between a start and stop.

```python
np.linspace(start, stop, num)
```
- Unlike `arange`, **both start and stop are included**.
- `num` = how many numbers to generate.

**Example**: `np.linspace(0, 1, 5)` → `[0.0, 0.25, 0.5, 0.75, 1.0]`

In [3]:
# ============================================================
# TOPIC 4.1 EXAMPLE: np.array()
# ============================================================

import numpy as np

# Creating a 1D array from a Python list
marks = np.array([85, 92, 78, 90, 88])
print("Student Marks Array:", marks)
print("Type:", type(marks))

print()

# # Creating a 2D array (matrix) from a list of lists
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D Array (Matrix):")
print(matrix)

Student Marks Array: [85 92 78 90 88]
Type: <class 'numpy.ndarray'>

2D Array (Matrix):
[[1 2 3]
 [4 5 6]]


In [4]:
# ============================================================
# TOPIC 4.2 EXAMPLE: np.arange()
# ============================================================

import numpy as np

# Counting from 0 to 9
a = np.arange(10)
print("0 to 9:", a)

# Counting from 1 to 10
b = np.arange(1, 11)
print("1 to 10:", b)

# Even numbers from 0 to 18 (step = 2)
c = np.arange(0, 20, 2)
print("Even numbers (0 to 18):", c)

# Counting backwards from 10 to 1
d = np.arange(10, 0, -1)
print("Countdown (10 to 1):", d)

0 to 9: [0 1 2 3 4 5 6 7 8 9]
1 to 10: [ 1  2  3  4  5  6  7  8  9 10]
Even numbers (0 to 18): [ 0  2  4  6  8 10 12 14 16 18]
Countdown (10 to 1): [10  9  8  7  6  5  4  3  2  1]


In [7]:
# ============================================================
# TOPIC 4.3 EXAMPLE: np.zeros()
# ============================================================

import numpy as np

# 1D array of 5 zeros
z1 = np.zeros(5)
print("1D Zeros:", z1)

# 2D array: 3 rows and 4 columns, all zeros
z2 = np.zeros((3, 4))
print("\n2D Zeros (3 rows x 4 cols):")
print(z2)

# Zeros with integer data type
z3 = np.zeros(5, dtype=int)
print("\nZeros as integers:", z3)

1D Zeros: [0. 0. 0. 0. 0.]

2D Zeros (3 rows x 4 cols):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Zeros as integers: [0 0 0 0 0]


In [5]:
# ============================================================
# TOPIC 4.4 EXAMPLE: np.ones()
# ============================================================

import numpy as np

# 1D array of 6 ones
o1 = np.ones(6)
print("1D Ones:", o1)

# 2D array: 2 rows and 3 columns, all ones
o2 = np.ones((2, 3))
print("\n2D Ones (2 rows x 3 cols):")
print(o2)

# Practical use: multiply ones by a constant to fill with that value
filled = np.ones(5) * 99
print("\nArray filled with 99 using ones trick:", filled)

1D Ones: [1. 1. 1. 1. 1. 1.]

2D Ones (2 rows x 3 cols):
[[1. 1. 1.]
 [1. 1. 1.]]

Array filled with 99 using ones trick: [99. 99. 99. 99. 99.]


In [7]:
# ============================================================
# TOPIC 4.5 EXAMPLE: np.full()
# ============================================================

import numpy as np

# 1D array of 5 elements, all filled with 7
f1 = np.full(5, 7.0)
print("Filled with 7:", f1)

# 2D array: 3 rows, 3 columns — all filled with 42
f2 = np.full((3, 3), 42)
print("\n2D Array filled with 42:")
print(f2)

# Fill with a float value
f3 = np.full(4, 3.14)
print("\nFilled with pi (approx):", f3)

Filled with 7: [7. 7. 7. 7. 7.]

2D Array filled with 42:
[[42 42 42]
 [42 42 42]
 [42 42 42]]

Filled with pi (approx): [3.14 3.14 3.14 3.14]


In [1]:
# ============================================================
# TOPIC 4.6 EXAMPLE: np.linspace()
# ============================================================

import numpy as np

# 5 evenly spaced values from 0 to 1 (both included)
ls1 = np.linspace(0, 1, 5)
print("0 to 1 in 5 steps:", ls1)

# 10 evenly spaced values from 0 to 100
ls2 = np.linspace(0, 100, 10)
print("\n0 to 100 in 10 steps:", ls2)

# Practical example: divide a semester into 6 equal time checkpoints
days = np.linspace(1, 45, 6)
print("\nTraining program checkpoints (Day numbers):", days)

print()
print("💡 Tip: linspace always INCLUDES both start and stop values!")

0 to 1 in 5 steps: [0.   0.25 0.5  0.75 1.  ]

0 to 100 in 10 steps: [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]

Training program checkpoints (Day numbers): [ 1.   9.8 18.6 27.4 36.2 45. ]

💡 Tip: linspace always INCLUDES both start and stop values!


---

## 📌 Topic 5: Array Attributes

### 🧑‍🏫 Theory

Every NumPy array has built-in **attributes** — properties that describe the array.  
You don't need to call them like functions (no parentheses `()`). Just use a **dot** and the attribute name.

| Attribute | What it tells you | Example |
|-----------|------------------|----------|
| `ndim` | Number of **dimensions** (1D, 2D, 3D, ...) | `arr.ndim` |
| `shape` | **Rows and Columns** (or size of each dimension) | `arr.shape` |
| `size` | **Total number of elements** in the array | `arr.size` |
| `dtype` | **Data type** of the elements (int, float, etc.) | `arr.dtype` |

### 🏫 Understanding `shape`

Shape is returned as a **tuple**:
- `(5,)` → 1D array with 5 elements
- `(3, 4)` → 2D array with 3 rows and 4 columns
- `(2, 3, 4)` → 3D array (2 blocks, 3 rows, 4 columns)

### 🏫 Understanding `dtype`

Common data types in NumPy:
- `int32` / `int64` → Integer numbers (like 1, 2, 100)
- `float32` / `float64` → Decimal numbers (like 3.14, 2.5)
- `bool` → True or False values
- `str_` / `<U5` → String values

In [10]:
# ============================================================
# TOPIC 5 EXAMPLE: Array Attributes
# ============================================================

import numpy as np

# --- 1D Array ---
arr1d = np.array([10, 20, 30, 40, 50])

print("=== 1D Array ===")
print("Array:", arr1d)
print("ndim  (dimensions):", arr1d.ndim)    # How many dimensions?
print("shape (rows x cols):", arr1d.shape)  # What is the shape?
print("size  (total elements):", arr1d.size) # How many elements total?
print("dtype (data type):", arr1d.dtype)    # What type of data?

print()

# --- 2D Array ---
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("=== 2D Array ===")
print("Array:")
print(arr2d)
print("ndim  (dimensions):", arr2d.ndim)     # 2D
print("shape (rows x cols):", arr2d.shape)   # (3, 4) = 3 rows, 4 columns
print("size  (total elements):", arr2d.size) # 3 * 4 = 12
print("dtype (data type):", arr2d.dtype)     # int

print()

# --- Float Array ---
float_arr = np.array([1.5, 2.7, 3.9])
print("=== Float Array ===")
print("Array:", float_arr)
print("dtype:", float_arr.dtype)  # float64

print()

# --- Specifying dtype at creation ---
int_arr = np.array([1.5, 2.9, 3.7], dtype=int)  # Convert float to int
print("=== Float converted to Int ===")
print("Array:", int_arr)   # Decimal part is dropped!
print("dtype:", int_arr.dtype)

=== 1D Array ===
Array: [10 20 30 40 50]
ndim  (dimensions): 1
shape (rows x cols): (5,)
size  (total elements): 5
dtype (data type): int64

=== 2D Array ===
Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim  (dimensions): 2
shape (rows x cols): (3, 4)
size  (total elements): 12
dtype (data type): int64

=== Float Array ===
Array: [1.5 2.7 3.9]
dtype: float64

=== Float converted to Int ===
Array: [1 2 3]
dtype: int64


---

## 📌 Topic 6: 1D Indexing and Slicing

### 🧑‍🏫 Theory

**Indexing** means accessing a **single element** from an array.  
**Slicing** means accessing a **range (subset) of elements** from an array.

---

### 🔢 Indexing Rules

NumPy uses **0-based indexing** — just like Python lists.

```
Array:  [10, 20, 30, 40, 50]
Index:  [ 0,  1,  2,  3,  4]   ← Positive index (left to right)
Index:  [-5, -4, -3, -2, -1]   ← Negative index (right to left)
```

- **Positive index**: Count from the **left**, starting at 0
- **Negative index**: Count from the **right**, starting at -1

---

### ✂️ Slicing Syntax

```python
array[start : stop : step]
```

- `start` → Index to begin (included)
- `stop`  → Index to end (**excluded** — not included)
- `step`  → Jump interval

If you leave any part blank, NumPy uses defaults:
- `start` defaults to `0`
- `stop` defaults to `end of array`
- `step` defaults to `1`

| Slice | Meaning |
|-------|---------|
| `arr[1:4]` | Elements at index 1, 2, 3 |
| `arr[:3]` | First 3 elements (0, 1, 2) |
| `arr[2:]` | From index 2 to the end |
| `arr[::2]` | Every 2nd element |
| `arr[::-1]` | Reverse the array |

In [11]:
# ============================================================
# TOPIC 6 EXAMPLE: 1D Indexing
# ============================================================

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print()

# --- Positive Indexing ---
print("arr[0]  (first element):", arr[0])   # 10
print("arr[2]  (third element):", arr[2])   # 30
print("arr[4]  (last element):", arr[4])    # 50

print()

# --- Negative Indexing ---
print("arr[-1] (last element):", arr[-1])   # 50
print("arr[-2] (second last):", arr[-2])    # 40
print("arr[-5] (first element):", arr[-5])  # 10

Array: [10 20 30 40 50]

arr[0]  (first element): 10
arr[2]  (third element): 30
arr[4]  (last element): 50

arr[-1] (last element): 50
arr[-2] (second last): 40
arr[-5] (first element): 10


In [12]:
# ============================================================
# TOPIC 6 EXAMPLE: 1D Slicing
# ============================================================

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Array:", arr)
print()

# --- Basic Slicing ---
print("arr[1:4]   (index 1,2,3):", arr[1:4])    # [20, 30, 40]
print("arr[:3]    (first 3):", arr[:3])           # [10, 20, 30]
print("arr[5:]    (from index 5):", arr[5:])      # [60, 70, 80]
print("arr[:]     (entire array):", arr[:])        # All elements

print()

# --- Slicing with Step ---
print("arr[::2]   (every 2nd):", arr[::2])        # [10, 30, 50, 70]
print("arr[1::2]  (odd positions):", arr[1::2])   # [20, 40, 60, 80]
print("arr[::-1]  (reversed):", arr[::-1])         # [80, 70, 60, ...]

print()

# --- Using negative index in slice ---
print("arr[-3:]   (last 3 elements):", arr[-3:])  # [60, 70, 80]

Array: [10 20 30 40 50 60 70 80]

arr[1:4]   (index 1,2,3): [20 30 40]
arr[:3]    (first 3): [10 20 30]
arr[5:]    (from index 5): [60 70 80]
arr[:]     (entire array): [10 20 30 40 50 60 70 80]

arr[::2]   (every 2nd): [10 30 50 70]
arr[1::2]  (odd positions): [20 40 60 80]
arr[::-1]  (reversed): [80 70 60 50 40 30 20 10]

arr[-3:]   (last 3 elements): [60 70 80]


---

## 📌 Topic 7: 2D Arrays

### 🧑‍🏫 Theory

A **2D array** is like a **table** (or a spreadsheet) with **rows** and **columns**.  
Think of it like a **classroom seating arrangement** — each seat has a row number and a column number.

```
        Col 0   Col 1   Col 2
Row 0 [  1       2       3  ]
Row 1 [  4       5       6  ]
Row 2 [  7       8       9  ]
```

To access element **6** (Row 1, Col 2), we write: `arr[1, 2]`

### 🏫 Creating a 2D Array

We pass a **list of lists** to `np.array()`.  
Each inner list becomes **one row**.

```python
arr = np.array([
    [1, 2, 3],   # Row 0
    [4, 5, 6],   # Row 1
    [7, 8, 9]    # Row 2
])
```

In [15]:
# ============================================================
# TOPIC 7 EXAMPLE: 2D Arrays
# ============================================================

import numpy as np

# Creating a 2D array (3 rows, 3 columns)
arr2d = np.array([
    [1, 2, 3],   # Row 0
    [4, 5, 6],   # Row 1
    [7, 8, 9]    # Row 2
])

print("2D Array:")
print(arr2d)

print()
print("ndim  :", arr2d.ndim)    # 2
print("shape :", arr2d.shape)   # (3, 3) = 3 rows, 3 columns
print("size  :", arr2d.size)    # 9 total elements
print("dtype :", arr2d.dtype)   # int

print()

# Real-life example: marks of 4 students in 3 subjects
# Rows = Students, Columns = Subjects (Maths, Science, English)
marks = np.array([
    [85, 90, 78],   # Student 0
    [92, 88, 95],   # Student 1
    [70, 75, 80],   # Student 2
    [60, 65, 72]    # Student 3
])

print("Student Marks Table (rows=students, cols=subjects):")
print(marks)
print("Shape:", marks.shape, "→", marks.shape[0], "students,", marks.shape[1], "subjects")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

ndim  : 2
shape : (3, 3)
size  : 9
dtype : int64

Student Marks Table (rows=students, cols=subjects):
[[85 90 78]
 [92 88 95]
 [70 75 80]
 [60 65 72]]
Shape: (4, 3) → 4 students, 3 subjects


---

## 📌 Topic 8: 2D Indexing and Slicing

### 🧑‍🏫 Theory

To access elements in a 2D array, we use **two indices**: one for **row** and one for **column**.

```python
arr[row_index, col_index]   # Access single element
arr[row_index]              # Access entire row
arr[:, col_index]           # Access entire column
```

---

### ✂️ 2D Slicing

Slicing works on **both dimensions** simultaneously:

```python
arr[row_start:row_stop, col_start:col_stop]
```

| Syntax | Meaning |
|--------|---------|
| `arr[0, 2]` | Element at row 0, col 2 |
| `arr[1]` | Entire row 1 |
| `arr[:, 2]` | Entire column 2 |
| `arr[0:2, 1:3]` | Rows 0-1, Columns 1-2 (submatrix) |
| `arr[:, :]` | All rows, all columns (full array) |

In [14]:
# ============================================================
# TOPIC 8 EXAMPLE: 2D Indexing
# ============================================================

import numpy as np

arr = np.array([
    [10, 20, 30],   # Row 0
    [40, 50, 60],   # Row 1
    [70, 80, 90]    # Row 2
])

print("2D Array:")
print(arr)
print()

# --- Single element access ---
print("arr[0, 0] (row 0, col 0):", arr[0, 0]) 
print("arr[1, 2] (row 1, col 2):", arr[1, 2])  
print("arr[2, 1] (row 2, col 1):", arr[2, 1]) 

print()

# --- Negative indexing in 2D ---
print("arr[-1, -1] (last row, last col):", arr[-1, -1])  # 90
print("arr[0, -1]  (first row, last col):", arr[0, -1])  # 30

print()

# --- Accessing full row ---
print("arr[1]    (entire row 1):", arr[1])    # [40, 50, 60]
print("arr[1, :] (same as above):", arr[2,:]) # [40, 50, 60]

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

arr[0, 0] (row 0, col 0): 10
arr[1, 2] (row 1, col 2): 60
arr[2, 1] (row 2, col 1): 80

arr[-1, -1] (last row, last col): 90
arr[0, -1]  (first row, last col): 30

arr[1]    (entire row 1): [40 50 60]
arr[1, :] (same as above): [70 80 90]


In [15]:
# ============================================================
# TOPIC 8 EXAMPLE: 2D Slicing
# ============================================================

import numpy as np

arr = np.array([
    [10, 20, 30, 40],   # Row 0
    [50, 60, 70, 80],   # Row 1
    [90, 100, 110, 120] # Row 2
])

print("2D Array:")
print(arr)
print()

# --- Accessing a full column ---
print("arr[:, 0] (column 0):", arr[:, 0])   # [10, 50, 90]
print("arr[:, 2] (column 2):", arr[:, 2])   # [30, 70, 110]

print()

# --- Submatrix (block of rows and columns) ---
print("arr[0:2, 1:3] (rows 0-1, cols 1-2):")
print(arr[0:2, 1:3])   # [[20, 30], [60, 70]]

print()

# --- First 2 rows, all columns ---
print("arr[:2, :] (first 2 rows):")
print(arr[:2, :])

print()

# --- Last column of all rows ---
print("arr[:, -1] (last column):", arr[:, -1])  # [40, 80, 120]

2D Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

arr[:, 0] (column 0): [10 50 90]
arr[:, 2] (column 2): [ 30  70 110]

arr[0:2, 1:3] (rows 0-1, cols 1-2):
[[20 30]
 [60 70]]

arr[:2, :] (first 2 rows):
[[10 20 30 40]
 [50 60 70 80]]

arr[:, -1] (last column): [ 40  80 120]


---

## 📌 Topic 9: Mathematical / Vectorized Operations

### 🧑‍🏫 Theory

One of NumPy's greatest powers is **vectorized operations** — applying a mathematical operation to **every element** of the array **without using a loop**.

### ➕ Arithmetic Operations

You can use standard operators `+`, `-`, `*`, `/`, `**` (power), `//` (floor division), `%` (modulo) directly on arrays.

```python
arr = np.array([1, 2, 3, 4])

arr + 10   → [11, 12, 13, 14]   # Add 10 to every element
arr * 3    → [ 3,  6,  9, 12]   # Multiply every element by 3
arr ** 2   → [ 1,  4,  9, 16]   # Square every element
```

### ➕ Element-wise Operations Between Two Arrays

When two arrays have the **same shape**, operations happen **element by element**:

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b  → [5, 7, 9]    # 1+4, 2+5, 3+6
a * b  → [4, 10, 18]  # 1*4, 2*5, 3*6
```

### 📐 Built-in Math Functions

NumPy has powerful built-in math functions:

| Function | What it does |
|----------|--------------|
| `np.sqrt(arr)` | Square root of each element |
| `np.abs(arr)` | Absolute value of each element |
| `np.exp(arr)` | e raised to the power of each element |
| `np.log(arr)` | Natural logarithm of each element |
| `np.round(arr, n)` | Round to n decimal places |

In [18]:
# ============================================================
# TOPIC 9 EXAMPLE: Mathematical / Vectorized Operations
# ============================================================

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)
print()

# --- Operations with a single number (scalar) ---
print("arr + 10 :", arr + 10)    # Add 10 to each element
print("arr - 1  :", arr - 1)     # Subtract 1 from each
print("arr * 3  :", arr * 3)     # Multiply each by 3
print("arr / 2  :", arr / 2)     # Divide each by 2
print("arr ** 2 :", arr ** 2)    # Square each element
print("arr % 2  :", arr % 2)     # Modulo (remainder when divided by 2)

print()

# --- Element-wise operations between two arrays ---
a = np.array([10, 20, 30, 40])
b = np.array([1,  2,  3,  4])

print("a:", a)
print("b:", b)
print("a + b:", a + b)    # [11, 22, 33, 44]
print("a - b:", a - b)    # [9, 18, 27, 36]
print("a * b:", a * b)    # [10, 40, 90, 160]
print("a / b:", a / b)    # [10.0, 10.0, 10.0, 10.0]

Original Array: [1 2 3 4 5]

arr + 10 : [11 12 13 14 15]
arr - 1  : [0 1 2 3 4]
arr * 3  : [ 3  6  9 12 15]
arr / 2  : [0.5 1.  1.5 2.  2.5]
arr ** 2 : [ 1  4  9 16 25]
arr % 2  : [1 0 1 0 1]

a: [10 20 30 40]
b: [1 2 3 4]
a + b: [11 22 33 44]
a - b: [ 9 18 27 36]
a * b: [ 10  40  90 160]
a / b: [10. 10. 10. 10.]


In [19]:
# ============================================================
# TOPIC 9 EXAMPLE: Built-in Math Functions
# ============================================================

import numpy as np

arr = np.array([4, 9, 16, 25, 36])
print("Array:", arr)
print()

# Square root
print("np.sqrt(arr)  :", np.sqrt(arr))

# Absolute value
neg_arr = np.array([-5, -3, 0, 2, 7])
print("np.abs(neg_arr):", np.abs(neg_arr))

# Rounding
decimals = np.array([1.234, 5.678, 9.012])
print("np.round(decimals, 1):", np.round(decimals, 1))

print()

# --- Practical Example: Grade Percentage Boost ---
raw_scores = np.array([70, 80, 55, 90, 65])
print("Raw Scores      :", raw_scores)

# Add 5 bonus marks
boosted = raw_scores + 5
print("After +5 bonus  :", boosted)

# Calculate percentage out of 110 (boosted max)
percentage = np.round((boosted / 110) * 100, 2)
print("Percentage (%)  :", percentage)

Array: [ 4  9 16 25 36]

np.sqrt(arr)  : [2. 3. 4. 5. 6.]
np.abs(neg_arr): [5 3 0 2 7]
np.round(decimals, 1): [1.2 5.7 9. ]

Raw Scores      : [70 80 55 90 65]
After +5 bonus  : [75 85 60 95 70]
Percentage (%)  : [68.18 77.27 54.55 86.36 63.64]


---

## 📌 Topic 10: Aggregation Functions

### 🧑‍🏫 Theory

**Aggregation** means summarizing a collection of numbers into a **single value**.  
NumPy provides powerful functions to compute statistics over an array.

| Function | What it computes |
|----------|-----------------|
| `np.sum()` | **Sum** of all elements |
| `np.mean()` | **Average (Mean)** of all elements |
| `np.min()` | **Minimum** (smallest) value |
| `np.max()` | **Maximum** (largest) value |
| `np.median()` | **Median** (middle value when sorted) |
| `np.std()` | **Standard Deviation** (spread of data) |
| `np.var()` | **Variance** (square of std deviation) |

---

### 🏫 Quick Definitions

- **Mean**: Add all values, divide by count. Example: Mean of [60, 80, 100] = (60+80+100)/3 = 80
- **Median**: Sort the values, pick the middle one. Example: Median of [60, 80, 100] = 80
- **Std Dev**: How far (on average) each value is from the mean. **Small std = data is close together, Large std = data is spread out**
- **Variance**: Standard Deviation squared. Another way to measure spread.

---

### 🗂️ Aggregation Along an Axis (for 2D arrays)

For 2D arrays, you can compute aggregations along:
- `axis=0` → **Down each column** (row-wise collapse)
- `axis=1` → **Across each row** (column-wise collapse)

```python
arr = [[1, 2, 3],
       [4, 5, 6]]

np.sum(arr, axis=0)  → [5, 7, 9]    # Sum of each column
np.sum(arr, axis=1)  → [6, 15]      # Sum of each row
```

In [20]:
# ============================================================
# TOPIC 10 EXAMPLE: Aggregation Functions (1D)
# ============================================================

import numpy as np

# Student test scores
scores = np.array([72, 85, 90, 60, 78, 95, 88, 55, 70, 82])
print("Scores:", scores)
print()

print("Sum      :", np.sum(scores))              # Total marks
print("Mean     :", np.mean(scores))             # Average marks
print("Minimum  :", np.min(scores))              # Lowest score
print("Maximum  :", np.max(scores))              # Highest score
print("Median   :", np.median(scores))           # Middle score (sorted)
print("Std Dev  :", np.round(np.std(scores), 2)) # How spread out the scores are
print("Variance :", np.round(np.var(scores), 2)) # Variance (std² )

print()
# Finding index of min and max
print("Index of Min score:", np.argmin(scores))  # Who got lowest?
print("Index of Max score:", np.argmax(scores))  # Who got highest?

Scores: [72 85 90 60 78 95 88 55 70 82]

Sum      : 775
Mean     : 77.5
Minimum  : 55
Maximum  : 95
Median   : 80.0
Std Dev  : 12.44
Variance : 154.85

Index of Min score: 7
Index of Max score: 5


In [21]:
# ============================================================
# TOPIC 10 EXAMPLE: Aggregation on 2D Arrays (with axis)
# ============================================================

import numpy as np

# 3 students, 4 subjects
marks = np.array([
    [80, 90, 70, 85],   # Student 0: Maths, Science, English, Hindi
    [60, 75, 88, 92],   # Student 1
    [95, 85, 78, 70]    # Student 2
])

print("Marks Table (rows=students, cols=subjects):")
print(marks)
print()

# Total of everything
print("Overall Total  :", np.sum(marks))
print("Overall Mean   :", np.mean(marks))

print()

# axis=1 → sum across each ROW (total per student)
print("Total per Student (axis=1):", np.sum(marks, axis=1))

# axis=0 → sum down each COLUMN (total per subject)
print("Total per Subject (axis=0):", np.sum(marks, axis=0))

print()

# Average per student
print("Avg per Student (axis=1) :", np.round(np.mean(marks, axis=1), 2))

# Average per subject
print("Avg per Subject (axis=0) :", np.round(np.mean(marks, axis=0), 2))

Marks Table (rows=students, cols=subjects):
[[80 90 70 85]
 [60 75 88 92]
 [95 85 78 70]]

Overall Total  : 968
Overall Mean   : 80.66666666666667

Total per Student (axis=1): [325 315 328]
Total per Subject (axis=0): [235 250 236 247]

Avg per Student (axis=1) : [81.25 78.75 82.  ]
Avg per Subject (axis=0) : [78.33 83.33 78.67 82.33]


---

## 📌 Topic 11: Boolean Masking / Filtering

### 🧑‍🏫 Theory

**Boolean masking** is a powerful way to **filter elements** from an array based on a **condition**.

Here's how it works in two steps:

**Step 1**: Apply a condition to the array → This gives you an array of `True`/`False` values (called a **boolean mask**).

```python
arr = np.array([10, 25, 5, 40, 15])
mask = arr > 15
# mask → [False, True, False, True, False]
```

**Step 2**: Use the mask to filter the original array — only `True` positions are kept:

```python
arr[mask]  → [25, 40]   # Only elements where mask is True
```

This can also be written in one line:

```python
arr[arr > 15]  → [25, 40]
```

---

### 🔗 Combining Conditions

Use `&` (AND) and `|` (OR) to combine multiple conditions.  
⚠️ Always wrap each condition in **parentheses `()`**!

```python
arr[(arr > 10) & (arr < 40)]   # Elements between 10 and 40
arr[(arr < 5) | (arr > 35)]    # Elements less than 5 OR greater than 35
```

In [ ]:
# ============================================================
# TOPIC 11 EXAMPLE: Boolean Masking / Filtering
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])
print("All Scores:", scores)
print()

# --- Step 1: Create a boolean mask ---
pass_mask = scores >= 60
print("Pass Mask (scores >= 60):", pass_mask)
# Output: [False True False True True False True True True True]

print()

# --- Step 2: Apply mask to filter ---
pass_scores = scores[pass_mask]
print("Passing Scores:", pass_scores)

# --- One-liner version ---
fail_scores = scores[scores < 60]
print("Failing Scores:", fail_scores)

print()

# --- Count of passing and failing students ---
print("Number of students who passed:", len(pass_scores))
print("Number of students who failed:", len(fail_scores))

In [ ]:
# ============================================================
# TOPIC 11 EXAMPLE: Combining Conditions
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])
print("Scores:", scores)
print()

# AND condition: Scores between 60 and 85 (Grade B students)
grade_b = scores[(scores >= 60) & (scores <= 85)]
print("Grade B (60–85):", grade_b)

# OR condition: Below 50 OR above 90 (Extremes)
extremes = scores[(scores < 50) | (scores > 90)]
print("Extremes (<50 or >90):", extremes)

# NOT condition: Scores that are NOT failing
not_failing = scores[~(scores < 60)]    # ~ means NOT
print("Not Failing (not <60):", not_failing)

print()

# Practical: Assign grade labels using boolean checks
print("Any score above 90?", np.any(scores > 90))    # True if at least one
print("All scores above 30?", np.all(scores > 30))   # True if all satisfy

---

## 📌 Topic 12: `np.where()`

### 🧑‍🏫 Theory

`np.where()` is like a **vectorized if-else statement**.  
It applies a condition element by element and returns one value if `True` and another if `False`.

### 🔤 Syntax

```python
np.where(condition, value_if_true, value_if_false)
```

### 🏫 Analogy

Think of it like checking every student's marks:

> *"If the score is 60 or more, write 'Pass'. Otherwise, write 'Fail'."*

With a regular Python loop, you'd need several lines of code.  
With `np.where()`, you do it in **one line**!

```python
np.where(scores >= 60, "Pass", "Fail")
```

---

### 📝 Two ways to use `np.where()`

**1. With condition + values** (if-else replacement):
```python
np.where(condition, true_value, false_value)
```

**2. With condition only** (returns indices where condition is True):
```python
np.where(condition)   # Returns a tuple of indices
```

In [2]:
# ============================================================
# TOPIC 12 EXAMPLE: np.where()
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])
print("Scores:", scores)
print()

# --- Basic np.where(): Pass or Fail ---
result = np.where(scores >= 60, "Pass", "Fail")
print("Pass/Fail Result:", result)

print()

# --- Replace values using np.where() ---
# Apply +5 bonus to students who failed (scored < 60), leave others unchanged
adjusted = np.where(scores < 60, scores + 5, scores)
print("Original Scores :", scores)
print("Adjusted Scores  :", adjusted)  # Only failing students get +5

print()

# --- Assign Grade Labels ---
grades = np.where(scores >= 85, "A",
         np.where(scores >= 70, "B",
         np.where(scores >= 60, "C", "F")))

print("Scores:", scores)
print("Grades :", grades)

Scores: [55 72 48 90 65 38 85 77 60 92]

Pass/Fail Result: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']

Original Scores : [55 72 48 90 65 38 85 77 60 92]
Adjusted Scores  : [60 72 53 90 65 43 85 77 60 92]

Scores: [55 72 48 90 65 38 85 77 60 92]
Grades : ['F' 'B' 'F' 'A' 'C' 'F' 'A' 'B' 'C' 'A']


In [5]:
# ============================================================
# TOPIC 12 EXAMPLE: np.where() to find indices
# ============================================================

import numpy as np

scores = np.array([55, 72, 48, 90, 65, 38, 85, 77, 60, 92])

# Find INDICES where scores > 80
indices = np.where(scores > 80)[0]
print("Indices where score > 80:", indices)      # Returns array of indices
print("Values at those indices  :", scores[indices]) # Get the actual values

print()

# Practical example: Find which students need remedial support
remedial_indices = np.where(scores < 50)[0]
print("Students needing remedial support (index):", remedial_indices)
print("Their scores:", scores[remedial_indices])

Indices where score > 80: [3 6 9]
Values at those indices  : [90 85 92]

Students needing remedial support (index): [2 5]
Their scores: [48 38]


---

## 🏋️ Practice Questions

> **Instructions:** Try to solve these on your own before looking at hints!  
> You can write your code in the cells provided below each question.

---

### ❓ Q1. Array Creation
Create the following arrays:
- (a) A 1D NumPy array of numbers from **5 to 50** in steps of **5** using `np.arange()`.
- (b) A 2D array of shape **(4, 4)** filled with the value **7** using `np.full()`.
- (c) An array of **8 evenly spaced values** between **0 and 1** using `np.linspace()`.

In [2]:
# Q1: Your answer here
import numpy as np

# (a) 5 to 50 in steps of 5
a1 = np.array(range(5,50,5))
print(a1)

# (b) 4x4 array filled with 7
a2 = np.empty((4,4))
a2.fill(7)
print(a2)

# (c) 8 evenly spaced values between 0 and 1
print(np.linspace(0,1,8))


[ 5 10 15 20 25 30 35 40 45]
[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


---

### ❓ Q2. Array Attributes
Create a 2D NumPy array of shape **(5, 3)** containing your own values.  
Then print its: `ndim`, `shape`, `size`, and `dtype`.

In [3]:
# Q2: Your answer here
import numpy as np

# Create the array and print its attributes
a2 = np.zeros((5,3))
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.dtype)
print(a2.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(5, 3)
float64
15


---

### ❓ Q3. Indexing and Slicing (1D)
Given the array: `arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])`

- (a) Access the **3rd element** (value 15).
- (b) Access the **last element** using negative indexing.
- (c) Slice the array to get `[20, 25, 30, 35]`.
- (d) Get every **alternate element** starting from index 0.
- (e) **Reverse** the entire array using slicing.

In [4]:
# Q3: Your answer here
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# (a) 3rd element
print(arr[2])
# (b) Last element
print(arr[-1])
# (c) [20, 25, 30, 35]
print(arr[3:7])
# (d) Every alternate element
print(arr[::2])
# (e) Reversed array
print(arr[::-1])

15
50
[20 25 30 35]
[ 5 15 25 35 45]
[50 45 40 35 30 25 20 15 10  5]


---

### ❓ Q4. 2D Array Operations
Create this array:
```
[[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
```
- (a) Access the value **60**.
- (b) Get the **entire second row** (row index 1).
- (c) Get the **entire first column**.
- (d) Extract the **top-left 2×2 submatrix** (`[[10,20],[40,50]]`).

In [13]:
# Q4: Your answer here
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# (a) Access 60
print(arr[1][2])
# (b) Second row
print(arr[1])
# (c) First column
print(arr[:,0])
# (d) Top-left 2x2
print(arr[:2, :2])

60
[40 50 60]
[10 40 70]
[[10 20]
 [40 50]]


---

### ❓ Q5. Vectorized Operations
Given: `prices = np.array([100, 250, 75, 300, 150, 220])`

- (a) Apply a **10% discount** on all prices.
- (b) Add a **flat ₹20 shipping charge** to all prices.
- (c) Find prices after **both** applying 10% discount and then adding ₹20 shipping.

In [ ]:
# Q5: Your answer here
import numpy as np

prices = np.array([100, 250, 75, 300, 150, 220])

# (a) 10% discount

# (b) +20 shipping

# (c) Both: 10% discount then +20 shipping


---

### ❓ Q6. Aggregation Functions
Given test scores of 8 students: `[62, 78, 55, 90, 83, 47, 71, 95]`

Calculate and print:
- (a) Total marks (sum)
- (b) Class average (mean)
- (c) Highest and lowest marks
- (d) Median score
- (e) Standard deviation (how spread out are the marks?)

In [ ]:
# Q6: Your answer here
import numpy as np

scores = np.array([62, 78, 55, 90, 83, 47, 71, 95])

# (a) Sum

# (b) Mean

# (c) Max and Min

# (d) Median

# (e) Std Dev


---

### ❓ Q7. Aggregation on 2D Array
Create this marks table (3 students, 3 subjects):
```
[[80, 70, 90],
 [60, 85, 75],
 [95, 65, 88]]
```
- (a) Find the **total score per student** (sum across each row).
- (b) Find the **average score per subject** (mean down each column).
- (c) Find the **overall maximum** score in the entire table.

In [ ]:
# Q7: Your answer here
import numpy as np

marks = np.array([[80, 70, 90],
                  [60, 85, 75],
                  [95, 65, 88]])

# (a) Total per student

# (b) Average per subject

# (c) Overall maximum


---

### ❓ Q8. Boolean Masking
Given temperatures: `temps = np.array([22, 35, 18, 40, 28, 15, 38, 25, 42, 30])`

- (a) Find all temperatures **above 30°C** (hot days).
- (b) Find all temperatures **between 20°C and 30°C** (comfortable days).
- (c) Count how many days were **below 20°C** (cold days).
- (d) Check if **any** day had temperature **above 40°C**.

In [ ]:
# Q8: Your answer here
import numpy as np

temps = np.array([22, 35, 18, 40, 28, 15, 38, 25, 42, 30])

# (a) Above 30°C

# (b) Between 20 and 30

# (c) Count of days below 20°C

# (d) Any day above 40°C?


---

### ❓ Q9. `np.where()` — Grade Assignment
Given scores: `scores = np.array([45, 62, 78, 91, 55, 83, 70, 38, 95, 66])`

Use `np.where()` to:
- (a) Label each score as `"Pass"` (≥ 60) or `"Fail"` (< 60).
- (b) Apply a **curved score**: Add 5 marks to anyone who scored **below 50**, leave others unchanged.
- (c) Assign grade **"Distinction"** if score ≥ 85, **"Merit"** if score ≥ 65, else **"Pass/Fail"** as appropriate.

In [ ]:
# Q9: Your answer here
import numpy as np

scores = np.array([45, 62, 78, 91, 55, 83, 70, 38, 95, 66])

# (a) Pass or Fail

# (b) Curved score (add 5 to scores < 50)

# (c) Grade assignment


---

### ❓ Q10. Mini Challenge — Put It All Together! 🏆

You are a teacher with the following data for **6 students** across **4 subjects**:  
*(Subjects: Maths, Science, English, Computer)*

```
Student 0: [82, 76, 90, 88]
Student 1: [55, 60, 72, 50]
Student 2: [91, 85, 78, 95]

```

Do the following:
- (a) Print the shape of the array.
- (b) Find the **total marks** for each student.
- (c) Find the **average marks** per subject.
- (d) Identify students whose **total marks are below 250** (struggling students).
- (e) Use `np.where()` to label each student's **total** as `"Good"` if ≥ 300, else `"Needs Improvement"`.

In [ ]:
# Q10: Your answer here
import numpy as np

marks = np.array([
    [82, 76, 90, 88],   # Student 0
    [55, 60, 72, 50],   # Student 1
    [91, 85, 78, 95],   # Student 2
    [40, 52, 61, 45],   # Student 3
    [70, 68, 80, 74],   # Student 4
    [88, 92, 85, 79]    # Student 5
])

# (a) Shape

# (b) Total per student

# (c) Average per subject

# (d) Struggling students (total < 250)

# (e) Label each student


---

## 🎉 Great Work! Day 1 Complete!

---

### 📝 Summary — What You Learned Today

| # | Topic | Key Takeaway |
|---|-------|--------------|
| 1 | What is NumPy? | Foundation library for numerical computing in Python |
| 2 | NumPy vs Lists | NumPy is faster, uses less memory, supports math operations |
| 3 | Importing NumPy | `import numpy as np` — universal convention |
| 4 | Array Creation | `array()`, `arange()`, `zeros()`, `ones()`, `full()`, `linspace()` |
| 5 | Array Attributes | `ndim`, `shape`, `size`, `dtype` |
| 6 | 1D Indexing & Slicing | `arr[i]`, `arr[start:stop:step]` |
| 7 | 2D Arrays | Like a table — rows and columns |
| 8 | 2D Indexing & Slicing | `arr[row, col]`, `arr[:, col]`, `arr[r1:r2, c1:c2]` |
| 9 | Math Operations | Vectorized — apply to all elements without loops |
| 10 | Aggregation | `sum`, `mean`, `min`, `max`, `median`, `std`, `var` |
| 11 | Boolean Masking | Filter elements using conditions |
| 12 | `np.where()` | Vectorized if-else — replace/label values conditionally |

---

### 🚀 Coming Up Next — Day 2

Stay tuned for **Day 2**, where we'll cover:
- Array reshaping
- Stacking and splitting arrays
- Random number generation
- Introduction to broadcasting

---

> 💡 **Pro Tip**: The best way to master NumPy is to **practice daily**.  
> Try re-solving the practice questions without looking at hints!  
> See you on Day 2! 🎯