In [2]:
import numpy as np

In [3]:
marks = np.array([[78, 85, 80, 90],
                  [65, 70, 75, 68],
                  [88, 92, 95, 91],
                  [55, 60, 58, 62],
                  [72, 76, 70, 80],
                  [90, 89, 94, 96]])

In [4]:
print(marks)

[[78 85 80 90]
 [65 70 75 68]
 [88 92 95 91]
 [55 60 58 62]
 [72 76 70 80]
 [90 89 94 96]]


In [5]:
print(marks.shape)

(6, 4)


In [6]:
print(marks.size)

24


In [7]:
print(marks.ndim)

2


In [8]:
print(marks.dtype)

int64


In [9]:
print(marks[0])

[78 85 80 90]


In [10]:
print(marks[1])

[65 70 75 68]


In [11]:
print(marks[5])

[90 89 94 96]


In [12]:
print(marks[2][2])

95


In [13]:
print(marks[3][3])

62


In [14]:
print(marks[:,0])

[78 65 88 55 72 90]


In [15]:
print(marks[:,1])

[85 70 92 60 76 89]


In [16]:
print(marks[:,2])

[80 75 95 58 70 94]


In [17]:
print(marks[:,3:])

[[90]
 [68]
 [91]
 [62]
 [80]
 [96]]


In [18]:
print(marks[:2][:2])

[[78 85 80 90]
 [65 70 75 68]]


In [19]:
print(marks[:3][:3])

[[78 85 80 90]
 [65 70 75 68]
 [88 92 95 91]]


In [20]:
print(marks[-2:][-2:])

[[72 76 70 80]
 [90 89 94 96]]


In [21]:
print(marks[:,1:3])

[[85 80]
 [70 75]
 [92 95]
 [60 58]
 [76 70]
 [89 94]]


In [22]:
print(marks[1:4])

[[65 70 75 68]
 [88 92 95 91]
 [55 60 58 62]]


In [23]:
print(marks[1:4, 1:3])

[[70 75]
 [92 95]
 [60 58]]


In [47]:
print(marks[1::2])

[[65 70 75 68]
 [55 60 58 62]
 [90 89 94 96]]


In [48]:
print(marks[::-1])

[[90 89 94 96]
 [72 76 70 80]
 [55 60 58 62]
 [88 92 95 91]
 [65 70 75 68]
 [78 85 80 90]]


In [ ]:
print(marks[:, ::-1])

[[90 80 85 78]
 [68 75 70 65]
 [91 95 92 88]
 [62 58 60 55]
 [80 70 76 72]
 [96 94 89 90]]


In [24]:
stocks = np.array([
    [20, 25, 22, 30],
    [35, 40, 38, 42],
    [15, 18, 20, 25]
])

In [25]:
print(stocks)

[[20 25 22 30]
 [35 40 38 42]
 [15 18 20 25]]


In [26]:
print(stocks.shape)

(3, 4)


In [27]:
print(stocks.size)

12


In [28]:
print(stocks.ndim)

2


In [29]:
print(stocks.dtype)

int64


In [30]:
print(stocks[0])

[20 25 22 30]


In [31]:
print(stocks[1])

[35 40 38 42]


In [32]:
print(stocks[2])

[15 18 20 25]


In [55]:
print(stocks[:,0])

[20 35 15]


In [57]:
print(stocks[:,3])

[30 42 25]


In [58]:
print(stocks[0,1])

25


In [59]:
print(stocks[1,2])

38


In [60]:
print(stocks[2,3])

25


In [62]:
print(stocks[:2])

[[20 25 22 30]
 [35 40 38 42]]


In [64]:
print(stocks[:,1:])

[[25 22 30]
 [40 38 42]
 [18 20 25]]


In [65]:
print(stocks[0:2,1:3])

[[25 22]
 [40 38]]


In [66]:
print(stocks[::-1])

[[15 18 20 25]
 [35 40 38 42]
 [20 25 22 30]]


In [68]:
print(stocks[:,::-1])

[[30 22 25 20]
 [42 38 40 35]
 [25 20 18 15]]
